### ISSUE TITLE
Focus traps and empty boxes

### ISSUE THREAD

**Issue by vhscom** [beynar/svelte-spotlight#2]
Currently when I <kbd>Tab</kbd> past an empty search box my cursor moves up to the window chrome. Focus should be kept within the modal until dismissed, giving it its modality. Please consider looking to [svelte-headlessui.goss.io](https://svelte-headlessui.goss.io) for inspiration. Thank you.

**Comment by beynar** [comment]
Fix in v2

**Comment by beynar** [comment]
Fix in V2 🎉
